# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c6a58609bb1e5980cd03c6264a1ff0ea0d7d66565f39f2be09d3af9e332c0f30c16872432b36f2ea014853411c15ea996565e0fba8ea278c52f42531abaf261

test:
  secret_key_base: b66d213968e59886122e146695f899d47901de8a202f1072790ae2c9d16a14b9ec517942dfec6daffc1222acd3489aa6dad0a3f5c36daaf4a34bc8d9e178bcde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
